doctrine:
    dbal:
        default_connection: default
        connections:
          default:
              url: '%env(DATABASE_URL)%'
          slave:
              url: '%env(DATABASE_SLAVE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        default_entity_manager: default
        entity_managers:
          default:
            connection: default
            mappings:
                App\Domain:
                    is_bundle: false
                    dir: '%kernel.project_dir%/src/Domain/Entity'
                    prefix: 'App\Domain\Entity'
                    alias: App\Domain
          slave:
            connection: slave
            mappings:
                App\Domain:
                    is_bundle: false
                    dir: '%kernel.project_dir%/src/Domain/Entity'
                    prefix: 'App\Domain\Entity'
                    alias: App\Domain

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
