create-employee:
    path: /api/create-employee
    controller: App\Ui\Api\Action\CreateEmployeeAction
    methods: POST

add-delegation:
    path: /api/add-delegation
    controller: App\Ui\Api\Action\AddDelegationAction
    methods: POST

delegations-list:
    path: /api/delegations-list/{id}
    controller: App\Ui\Api\Action\DelegationsListAction
    methods: GET
